# 服务配置
server:
  port: 9300
  servlet:
    context-path: /
    encoding:
      force: true
      charset: UTF-8
    session:
      timeout: 30m
# spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zach-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/xxx
    username: xxx
    password: xxx
  # Redis配置
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 10
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
  # 配置文件上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#minio配置
minio:
  endpoint: http://localhost:8226
  access-key: xxx
  secret-key: xxx
#普罗米修斯
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
#Mybatis-plus
mybatis-plus:
  mapper-locations:
    classpath*: mapper/**/*Mapper.xml
  global-config:
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#图数据库nebula
nebula:
  address[0]:
    host: xxx
    port: 9669
  username: xxx
  password: xxx
  reconnect: false
  idleTime: 10000
  maxConnSize: 1000
# 日志级别: DEBUG INFO WARN ERROR
logging:
  level:
    root: WARN
    com.graph: DEBUG
    org.quartz: WARN
    org.springframework: WARN
# openApi-ui
springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /swagger
  #包扫描路径
  packages-to-scan: com.zach.modular
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    #分组名
    - group: zach
      #按包路径匹配
      packagesToScan: com.zach.modular.*
